global:
  namespace: "staging"

movie:
  tag: "staging"
  environment:
    POSTGRES_USER: "movie_db_username_staging"
    POSTGRES_PASSWORD: "movie_db_password_staging"
    POSTGRES_DB: "movie_db_staging"
    POSTGRES_HOST: "movie_db_staging"

cast:
  tag: "staging"
  environment:
    POSTGRES_USER: "cast_db_username_staging"
    POSTGRES_PASSWORD: "cast_db_password_staging"
    POSTGRES_DB: "cast_db_staging"
    POSTGRES_HOST: "cast-staging"

movieDB:
  POSTGRES_USER: "movie_db_username_staging"
  POSTGRES_PASSWORD: "movie_db_password_staging"
  POSTGRES_DB: "movie_db_staging"
  POSTGRES_HOST: "movie-staging"

castDB:
  POSTGRES_USER: "cast_db_username_staging"
  POSTGRES_PASSWORD: "cast_db_password_staging"
  POSTGRES_DB: "cast_db_staging"