apiVersion: v1
kind: Service
metadata:
  name: cast-db-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: movie-db-deployment
  ports:
   - name: TCP
     port: {{ .Values.castDB.port }}
     targetPort: {{ .Values.castDB.port }}
  