apiVersion: v1
kind: Service
metadata:
  name: cast-db-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: movie-db-deployment
  ports:
   - name: tcp
     port: {{ .Values.castDB.port }}
     targetPort: {{ .Values.castDB.port }}
  