apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cast-db-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.castDB.volume.size }}