apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: movie-db-statefulset
  namespace: {{ .Values.global.namespace }}
  labels:
    app: movie-db-statefulset
spec:
  replicas: {{ .Values.movieDB.replicas }}
  selector:
    matchLabels:
      app: movie-db-statefulset
  template:
    metadata:
      labels:
        app: movie-db-statefulset
    spec:
      containers:
      - name: movie-db-statefulset
        image: {{ .Values.movieDB.image }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.movieDB.POSTGRES_DB }}
        - name: POSTGRES_USER
          value: {{ .Values.movieDB.POSTGRES_USER }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.movieDB.POSTGRES_PASSWORD }}
        - name: DATABASE_URI
          value: postgresql://{{ .Values.movie.environment.POSTGRES_USER }}:{{ .Values.movie.environment.POSTGRES_PASSWORD }}@{{ .Values.movie.environment.POSTGRES_HOST }}/{{ .Values.movie.environment.POSTGRES_DB }}
        - name: CAST_SERVICE_HOST_URL
          value: http://cast-service:{{ .Values.movie.port }}/api/v1/casts/
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: {{ .Values.movieDB.pvcName }}
      volumes:
      - name: {{ .Values.movieDB.pvcName }}
        persistentVolumeClaim:
          claimName: {{ .Values.movieDB.pvcName }}