apiVersion: v1
kind: Service
metadata:
  name: movie-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.movie.port }}
    targetPort: {{ .Values.movie.port }}
  selector:
    app: movie-service