apiVersion: v1
kind: Service
metadata:
  name: movie-db-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: movie-db-deployment
  ports:
   - name: TCP
     port: {{ .Values.movieDB.port }}
     targetPort: {{ .Values.movieDB.port }}