apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-db-deployment
  namespace: {{ .Values.global.namespace }}
  labels:
    app: movie-db-deployment 
spec:
  replicas: {{ .Values.movieDB.replicas }}
  selector:
    matchLabels:
      app: movie-db-deployment
  template:
    metadata:
      labels:
        app: movie-db-deployment
    spec:
      containers:
      - name: movie-db-deployment
        image: {{ .Values.movieDB.image }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.movieDB.POSTGRES_DB }}
        - name: POSTGRES_USER
          value: {{ .Values.movieDB.POSTGRES_USER }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.movieDB.POSTGRES_PASSWORD }}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: {{ .Values.movieDB.pvcName }}
      volumes:
      - name: {{ .Values.movieDB.pvcName }}
        persistentVolumeClaim:
          claimName: {{ .Values.movieDB.pvcName }}