apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-db-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.movieDB.volume.size }}