apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.nginx.port }}
  selector:
    app: nginx